### PR TITLE
[ddnet_properties] Add more tiles, group similar tiles

### PR DESCRIPTION
**Pull request by Patiga**
Grouped some tiles together which have similar purposes. e.g. one tile to give a passing tee endless hook, one to give endless hook map-wide.

Maybe put on hold at least until it got successfully deployed

### CODE REVIEW

**Comment by def-** [comment]
Fixes https://github.com/heinrich5991/libtw2/issues/50 (partially? maybe it's enough)

**Comment by def-** [comment]
Seems to be missing a few tiles we were using before: BONUS, OLDLASER

**Comment by Patiga** [comment]
@heinrich5991 I don't understand the failed check, I suppose I shouldn't have implemented those functions for `LeI16` by hand?
I don't see a script generating those implementations yet.

**Comment by heinrich5991** [comment]
Can this be merged?

**Comment by Patiga** [comment]
@def- Is everything working properly now?

**Comment by def-** [comment]
Yes, seems fine.

**Comment by heinrich5991** [comment]
Thanks a lot!

**Pull request merged**
