### PR TITLE
CI: Pip install huffman

### PR DESCRIPTION
**Pull request by ChillerDragon**

### CODE REVIEW

**Comment by ChillerDragon** [comment]
Should probably test installing it from the local source not from pypi. But I could not find the readme with the build instructions for the python package.

**Comment by ChillerDragon** [comment]
This pipeline used to pass for me 3 months ago https://github.com/ChillerDragon/teeworlds-web-traffic-decoder/commits/master/

**Comment by heinrich5991** [comment]
> Should probably test installing it from the local source not from pypi. But I could not find the readme with the build instructions for the python package.

Yes. I believe it was "do what you do to get any Python project built". I had to look it up again, found it at https://packaging.python.org/en/latest/tutorials/packaging-projects/: `python -m build`.

**Comment by ChillerDragon** [comment]
I didn't even see the [pyproject.toml](https://github.com/heinrich5991/libtw2/blob/f3c8840d756bc06e436656c16f48f02bcb4ce8b3/uniffi/huffman/pyproject.toml) because i was looking in the huffman directory not in uniffi.

**Comment by ChillerDragon** [comment]
It is now building, installing and running the python package.

**Comment by heinrich5991** [comment]
I added it to the existing CI. Thanks for your PR which prompted me to do this. I wanted to improve upon this PR in two ways:
1) It tested in three different Python versions which I didn't find necessary.
2) The unit test was quite ad-hoc. I added structured Python unit tests instead.

Superseded by 83f22dbfe713682f7c528473c2f727049928a9dd.

**Pull request closed without merging**
