### PR TITLE
Replace try!() with ?

### PR DESCRIPTION
**Pull request by Fireball-Teeworlds**
Most of the replacements have been done with rerast: https://users.rust-lang.org/t/automatically-replace-all-try-with/16873.

A few (around 20) were done manually since the script has skipped them for some reason.

Both `cargo build` and `cargo test` succeed.

### CODE REVIEW

**Comment by Fireball-Teeworlds** [comment]
This fixes a lot of warnings from `cargo build`.

**Comment by heinrich5991** [comment]
Hi, and thanks for your interest in this project. As you can see, I haven't really done anything for this project in the last years, sorry for that.

About your pull request: Looks fine, however there's a couple of generated files that you changed. They're unfortunately not clearly marked, but I have added a GitHub actions check for them. If you rebase your pull request on master, you should see where you edited generated files.

**Comment by heinrich5991** [comment]
Hm, I don't have a useful error message in the CI. You can try running `./generate_all` locally in the main directory, then `git diff` will show the differences between generated files and the output of the generating scripts.

**Comment by Fireball-Teeworlds** [comment]
Thanks, that's what I'm doing at the moment :)

**Comment by Fireball-Teeworlds** [comment]
Seems that my replacements were consistent: updated generators now produce exactly the same files as I've submitted originally.

**Comment by heinrich5991** [comment]
Nice, thanks for the efforts!

**Pull request merged**
