### PR TITLE
stats_browser: print human-friendly names instead of base64 representation

### PR DESCRIPTION
**Pull request by ProgVal**

### CODE REVIEW

**Comment by heinrich5991** [comment]
The output of this module is imitating another program, hence it cannot be changed to output bare strings. You could add another module that outputs the changes in a way you want.

**Comment by ProgVal** [comment]
What about a `--pretty` option?

**Comment by heinrich5991** [comment]
What is your use case, what information do you want to extract? Just printing the strings would make automatic parsing hard, as you wouldn't have any delimiter anymore (player names or server names could contain tabs).

**Comment by ProgVal** [comment]
Indeed.
I don't have any use case, I just thought it would be prettier.

**Pull request closed without merging**
